### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by jessymilare**
Fixes a few bugs with &LABEL and declarations.

### CODE REVIEW

**Comment by scymtym** [comment]
Thank you for finding and working on fixing these problems.

Regarding `&labels`, I think something like
```lisp
(defmacro mergable-labels (bindings &body body)
  `(labels ,bindings ,@body))

(define-let+-expansion (&labels (function-name lambda-list
                                               &body function-body)
                                :uses-value? nil)
  "LET+ form for function definitions.  Expands into an LABELS, thus allowing recursive functions."
  (if (typep (first body) '(cons (eql mergable-labels)))
      (destructuring-bind (bindings &rest first-body) (rest (first body))
        (assert (null (rest body)))
        `(mergable-labels ((,function-name ,lambda-list ,@function-body)
                           ,@bindings)
           ,@first-body
           ,@(rest body)))
      `(mergable-labels ((,function-name ,lambda-list ,@function-body))
         ,@body)))
```
could be a bit cleaner. What do you think?

**Comment by jessymilare** [comment]
> could be a bit cleaner. What do you think?

Certainly, I'll change it.

**Comment by jessymilare** [comment]
I kept the test

```
  (if (and (null (rest body))                                                               
           ;; otherwise, the rest of BODY would be wrongly put inside LABELS scope          
           (typep (first body) '(cons (eql mergeable-labels))))
      ...)
```

because `(rest body)` shouldn't not be inside the scope of `mergeable-labels`. Probably won't make much difference, since this macro can only come from `let+` expansion, but doesn't hurt to check.

**Comment by scymtym** [comment]
I added your commit which addresses the declaration problem to master.

I would like to address the labels merging problem like this https://github.com/sharplispers/let-plus/commit/83a84dd528d7fffa5490dc9c5dcf99aaae37948d.
This version has
* `(assert (null (rest body)))` from my proposal since I'm convinced `mergable-labels` can only come from expanding `let+` forms which means there should only ever be one body form
* a slightly extended test

Would you like to be the commit author despite the modifications I made?

**Comment by jessymilare** [comment]
Yes, please, I would like to be the commit author. Your solution is better.

**Comment by scymtym** [comment]
Added to master as discussed. Thank you.

**Pull request closed without merging**
